### Build a DNN using Keras with `RELU` and `ADAM`

#### Load tensorflow

In [0]:
%tensorflow_version 2.x

In [0]:
import tensorflow as tf
import numpy as np

In [34]:
print(tf.__version__)

2.1.0-rc1


#### Collect Fashion mnist data from tf.keras.datasets 

In [0]:
from keras.datasets import fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

#### Change train and test labels into one-hot vectors

In [0]:
trainY = tf.keras.utils.to_categorical(y_train)
testY = tf.keras.utils.to_categorical(y_test)

In [37]:
print(trainY.shape)
print('First 5 examples now are: ', trainY[0:5])

(60000, 10)
First 5 examples now are:  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Build the Graph

#### Initialize model, reshape & normalize data

In [39]:
x_train_reshape = x_train.reshape(60000, 784)
print(x_train.shape)
x_test_reshape = x_test.reshape(10000, 784)
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [0]:
from sklearn.preprocessing import Normalizer
transformer = Normalizer()
train_x = transformer.fit_transform(x_train_reshape)
test_x = transformer.transform(x_test_reshape)

In [0]:
tf.keras.backend.clear_session()
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dense, Flatten, MaxPool2D

#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [0]:
model = Sequential()
model.add(Dense(200, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(tf.keras.layers.Dropout(0.25))

### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [0]:
model.add(Dense(10, activation='softmax'))

In [0]:
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', metrics=['accuracy'])

In [45]:
model.fit(train_x,trainY,          
          validation_data=(test_x,testY),
          epochs=10,
          batch_size=28)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 9s 152us/sample - loss: 0.5665 - accuracy: 0.7944 - val_loss: 0.4416 - val_accuracy: 0.8399
Epoch 2/10
60000/60000 [==============================] - 9s 144us/sample - loss: 0.3946 - accuracy: 0.8561 - val_loss: 0.3916 - val_accuracy: 0.8557
Epoch 3/10
60000/60000 [==============================] - 9s 147us/sample - loss: 0.3549 - accuracy: 0.8709 - val_loss: 0.3726 - val_accuracy: 0.8651
Epoch 4/10
60000/60000 [==============================] - 8s 140us/sample - loss: 0.3266 - accuracy: 0.8797 - val_loss: 0.3562 - val_accuracy: 0.8696
Epoch 5/10
60000/60000 [==============================] - 8s 133us/sample - loss: 0.3086 - accuracy: 0.8860 - val_loss: 0.3652 - val_accuracy: 0.8704
Epoch 6/10
60000/60000 [==============================] - 8s 131us/sample - loss: 0.2920 - accuracy: 0.8924 - val_loss: 0.3419 - val_accuracy: 0.8761
Epoch 7/10
60000/60000 [==========================

In [51]:
model.evaluate(test_x,testY)

10000/10000 [==============================] - 1s 55us/sample - loss: 0.3322 - accuracy: 0.8838


[0.3322392520546913, 0.8838]